zotero:
  user_id: ${oc.env:ZOTERO_ID}
  api_key: ${oc.env:ZOTERO_KEY}
  include_path:
    - "01EDA/**"
    - "02 大模型/**"

email:
  sender: ${oc.env:SENDER}
  receiver: ${oc.env:RECEIVER}
  smtp_server: smtp.qq.com
  smtp_port: 465
  sender_password: ${oc.env:SENDER_PASSWORD}

llm:
  api:
    key: ${oc.env:OPENAI_API_KEY}
    base_url: ${oc.env:OPENAI_API_BASE}
  api_mode: chat_completion
  generation_kwargs:
    model: deepseek-flash
  language: Chinese

source:
  arxiv:
    category: ["cs.AI", "cs.LG", "cs.CL", "cs.MA", "cs.AR", "cs.ET", "cs.LO", "cs.PL", "cs.SE", "cs.CV", "cs.CE", "eess.SY", "eess.SP", "math.NA"]
    include_cross_list: true

executor:
  debug: ${oc.env:DEBUG,null}
  send_empty: false
  max_paper_num: 30
  source: ['arxiv']
  reranker: local
